services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/chatbot:cached
    command: sleep infinity
    environment:
      - "DOTNET_ENVIRONMENT=Development"
      - "ASPNETCORE_ENVIRONMENT=Development"
